apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Druva's component
  description: Adding custom component.
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: my-team
